name: Validar novo PR

on:
  pull_request:

jobs:
  validar-pr:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validar titulo do PR
        id: pr_valido
        # Valida que o PR tem o titulo no formato certo. Regras:
        # Ele deve começar com o nível de alteração: [fix], [feat] ou [major]
        # Ou deve ser um PR de release: [release] Atualizar branch develop pós release

        run: |
          PR_TITLE=$(echo ${{ github.event.pull_request.title }} | tr '[:upper:]' '[:lower:]')
          PR_BRANCH=$(echo ${{ github.head_ref }} | sed 's/refs\/heads\///')
          
          if [[ $PR_TITLE =~ ^\[release\].*v[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
              echo "Nome da branch é válido"
          elif [[ $PR_TITLE =~ ^\[(feat|major)\].*$ ]]; then
              if [[ $PR_BRANCH =~ ^hotfix/.*$ ]]; then
                  echo "FECHAR_PR='Branchs HOTFIX não podem ter título de PR com [feat] ou [major]'" >> $GITHUB_OUTPUT
              else
                echo "Título do PR válido"
              fi
          elif [[ $PR_TITLE =~ ^\[(fix)\].*$ ]]; then
              echo "Título do PR válido"
          else
              echo "Título do PR inválido"
              echo "FECHAR_PR='Titulo de PR inválido! Deveria começar com [fix], [feat] ou [major]'" >> $GITHUB_OUTPUT
          fi

      - name: Validar nome da branch
        id: branch_valida
        # Valida que a BRANCH tem o nome válido. Regras:
        # * Branch do “próximo lançamento”: develop
        # * Branches de desenvolvimento de funcionalidades: feat/xpto
        # * Branches de desenvolvimento de correções de bug: bugfix/xpto
        # * Branches de versão canditadas a lançamento: v0.0.0
        #       obs: somente para a master
        # * Branches de correções de emergência: hotfix/xpto
        #       obs: somente para a master
        run: |
          PR_BRANCH=$(echo ${{ github.head_ref }} | sed 's/refs\/heads\///')
          BRANCH_DESTINO_DO_PR=$(echo ${{ github.base_ref }} | sed 's/refs\/heads\///')
          
          if [[ $PR_BRANCH =~ ^feat/.*$ || $PR_BRANCH =~ ^bugfix/.*$ || $PR_BRANCH =~ ^master$ ]]; then
              echo "Nome da branch é válido"
          elif [[ $PR_BRANCH =~ ^hotfix/.*$ ]]; then
              if [[ $BRANCH_DESTINO_DO_PR == "master" ]]; then
                  echo "Nome da branch é válido"
              else
                  echo "FECHAR_PR='PR com branch HOTFIX só pode ser feito para a master'" >> $GITHUB_OUTPUT
              fi
          elif [[ $PR_BRANCH =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Nome da branch é válido"
              if [[ $BRANCH_DESTINO_DO_PR != "master" ]]; then
                  echo "FECHAR_PR='PR de branch de versão (v0.0.0) só pode ser feito para a master'" >> $GITHUB_OUTPUT
              fi
          else
              echo "Nome da branch é inválido"
              echo "FECHAR_PR='Nome de branch inválido! Nomes aceitos: `develop`, `feat/xpto`, `bugfix/xpto`, `v0.0.0` e `hotfix/xpto`'" >> $GITHUB_OUTPUT
          fi

      - name: Pegar arquivos modificados
        id: changed-files-yaml
        uses: tj-actions/changed-files@v43
        with:
          files_yaml: |
            arquivos_nativos_ou_libs:
              - 'android/**'
              - 'ios/**'
              - 'package.json'
              - 'yarn.lock'

      - name: Validar se não alterou código nativou ou libs se for HOTFIX
        id: branch_hotfix_valida
        if: steps.changed-files-yaml.outputs.arquivos_nativos_ou_libs_any_changed == 'true'
        run: |
          PR_BRANCH=$(echo ${{ github.head_ref }} | sed 's/refs\/heads\///')
          
          if [[ $PR_BRANCH =~ ^hotfix/.*$ ]]; then
              echo "Branchs HOTFIX não podem alterar código nativo ou bibliotecas"
              echo "FECHAR_PR='Branchs HOTFIX não podem alterar código nativo ou bibliotecas'" >> $GITHUB_OUTPUT
          fi

      - name: Fechar PR se for preciso com a mensagem do motivo
        if: always()
        env:
          GH_TOKEN: ${{ secrets.DEV_USER_TOKEN }}
        run: |
          if [[ "${{ steps.pr_valido.outputs.FECHAR_PR }}" != "" ]]; then
              MENSAGEM="${{ steps.pr_valido.outputs.FECHAR_PR }}"
          elif [[ "${{ steps.branch_valida.outputs.FECHAR_PR }}" != "" ]]; then
              MENSAGEM="${{ steps.branch_valida.outputs.FECHAR_PR }}"
          elif [[ "${{ steps.branch_hotfix_valida.outputs.FECHAR_PR }}" != "" ]]; then
              MENSAGEM="${{ steps.branch_hotfix_valida.outputs.FECHAR_PR }}"
          else
              exit 0
          fi
  
          gh pr comment ${{ github.event.pull_request.number }} --body "$MENSAGEM"
          gh pr close ${{ github.event.pull_request.number }}

      - name: Executar testes
        # se for um PR da branch master para a develop não precisa rodar os testes
        if: ${{ github.base_ref }} != 'master'
        uses: ./.github/rodar-testes
